# Generated by Django 6.1 on 2026-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
