# Generated by Django 5.2.7 on 2025-11-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
