# Generated by Django 6.1 on 2026-08-29 07:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('departure_datetime', models.DateTimeField()),
                ('seats_total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('seats_available', models.PositiveSmallIntegerField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('STARTED', 'Démarré'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['departure_datetime'],
            },
        ),
    ]
