# Generated by Django 6.1 on 2026-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOOKING', 'Réservation'), ('TRIP', 'Trajet'), ('PAYMENT', 'Paiement'), ('REVIEW', 'Avis'), ('SYSTEM', 'Système'), ('MESSAGE', 'Message')], default='SYSTEM', max_length=20),
        ),
    ]
